name: campusease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.0.2
 
  qr_flutter: ^4.0.0
  pdf: ^3.11.3
  printing: ^5.14.0
  get: ^4.6.6
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.1.2
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  google_generative_ai: ^0.4.0
  file_picker: ^8.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1



flutter_launcher_icons:
  android: true
  ios: true
  macos:
    image_path: "assets/icon/app_icon.png"
  windows:
    image_path: "assets/icon/app_icon.png"
  web:
    image_path: "assets/icon/app_icon.png"
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpeg